#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     HTSMUX,              sensorI2CCustom)
#pragma config(Sensor, S3,     gyro,                sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     us,                  sensorSONAR)
#pragma config(Motor,  motorA,          red,           tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          green,         tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorC,          yellow,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     conveyorArmMotor, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     conveyorMotor, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     leftMotor,     tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     rightMotor,    tmotorNormal, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    ,                     tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    rightGoalHolder,      tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    preloadServo,         tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    possessionServo,      tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    leftGoalHolder,       tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    bridgeServo,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an Tetrix robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "LEGOLS-driver.h"
#include "FITBIncludes.c"
bool sensorDebug = false;
/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
    HTSMUXinit();//           Init sensor Muxer
	  HTSMUXscanPorts(HTSMUX);//^^^^^^^^^^^^^^^^^
	  //init more sensors on the muxer
	  LSsetActive(msensor_S2_3); //init goal grabbed lsensor
	  LSsetActive(msensor_S2_2); //init lsensor on the bridge arm
    servo[preloadServo] =   255;
    servo[rightGoalHolder] =  0;
    servo[leftGoalHolder] = 207;
    servo[bridgeServo] =    160;
    servo[possessionServo] = 0;
    return;
}
  //Ultrasound is on Mux2

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
void watchPreloads()
{
  int indx = 0;
  while (indx != 10)
  {
    if (LSvalNorm(msensor_S2_3) >= 50) servo[preloadServo] = 50;
    else if (LSvalNorm(msensor_S2_3) > 30) servo[leftGoalHolder] = 160;
    else servo[leftGoalHolder] = 207; servo[preloadServo] = 255;
    ++indx;
  }
}


//moveDist([left]power, length, [right]power, coast);
task main()
{
  initializeRobot();
  waitForStart(); // Wait for the beginning of autonomous phase.
  //turnDeg(40, "left", 40);
  //SensorValue[S4] >= 200

  if (sensorDebug)
  {
    while (true)
    {
      eraseDisplay();
      nxtDisplayBigTextLine(3, "GLS: %d", LSvalNorm(msensor_S2_3));
      wait10Msec(1);
    }
  }
  if (SensorValue[S4] >= 200)
  {
    //in one of the following boxes:
    //-----------
    //|X        |
    //|         |
    //|         |
    //|        X|
    //-----------
    //good val = 35
  moveDist(20, 44.5);
  servo[bridgeServo] = 35;
  wait1Msec(250);
  //a turn
  moveDist(20, 33, 0);
  wait1Msec(250);
  moveDist(20, 33.5);
  watchPreloads();
  //pack into
  wait1Msec(250);
  servo[leftGoalHolder] = 160;
  servo[rightGoalHolder] = 0;
  wait1Msec(200);
  motor[leftMotor] = 15;
  motor[rightMotor] = 15;
  wait1Msec(200);
  //LSvalNorm(msensor_S2_3) >= 40
  if (true)
  {
    //servo[preloadServo] = 50;
    wait1Msec(150);
  }
  wait1Msec(200);
  motor[leftMotor] = 0;
  motor[rightMotor] = 0;
  servo[leftGoalHolder] = 160;
  servo[rightGoalHolder] = 0;
  servo[bridgeServo] = 160;
  wait1Msec(100);
}
else if (SensorValue[S4] < 200)
{
    //in one of the following boxes:
    //-----------
    //|        X|
    //|         |
    //|         |
    //|X        |
    //-----------
  moveDist(20, 44.5);
  wait1Msec(250);
  //a turn
  turnTime(30, "right", 1750);
  wait1Msec(250);
  servo[bridgeServo] = 35;
  moveDist(25, 5);
  wait1Msec(150);
  moveDist(22, 15, 0);
  wait1Msec(100);
  moveDist(20, 28);
  watchPreloads();
  //pack into
  wait1Msec(250);
  servo[leftGoalHolder] = 160;
  servo[rightGoalHolder] = 0;
  wait1Msec(200);
  motor[leftMotor] = 12;
  motor[rightMotor] = 12;
  wait1Msec(300);

  if (LSvalNorm(msensor_S2_3) >= 40)
  {
    servo[preloadServo] = 50;
    wait1Msec(150);
  }
  wait1Msec(200);
  motor[leftMotor] = 0;
  motor[rightMotor] = 0;
  servo[leftGoalHolder] = 160;
  servo[rightGoalHolder] = 0;
  servo[bridgeServo] = 160;
  wait1Msec(100);
}

}
