#pragma config(Hubs,  S3, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S3_C1_1,     rightMotor,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     leftMotor,    tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//TJoystick joystick;

int leftMotorPower, rightMotorPower;
bool up, down, leftPowerDirectionUp, rightPowerDirectionUp;
bool nudgeForward, nudgeBackward, nudgeLeft, nudgeRight;

int returnDrivingFactor ()
{
  int drivingFactor;
  bool halfSpeed, threeQuarterSpeed, quarterSpeed;
  halfSpeed = joy1Btn(2);
  threeQuarterSpeed = joy1Btn(3);
  quarterSpeed = joy1Btn(4);
  if (halfSpeed)
  {
    drivingFactor = 2;
  }
  else if (quarterSpeed)
  {
    drivingFactor = 4;
  }
  return drivingFactor;
}


  /*
  up = joy1Btn(5);
  down = joy1Btn(7);
  if (up)
  {
    leftPowerDirectionUp = true;
  }
  else if (down)
  {
    leftPowerDirectionUp = false;
  }
  if (leftPowerDirectionUp)
  {
    if (leftMotorPower+5>0)
    {
    leftMotorPower = leftMotorPower + 5;
    }
  }
  else if (!leftPowerDirectionUp)
  {
    if (leftMotorPower-5>0)
    {
    leftMotorPower = leftMotorPower - 5;
    }*/



  /*
  up = joy1Btn(6);
  down = joy1Btn(8);
  if (up)
  {
    rightPowerDirectionUp = true;
  }
  else if (down)
  {
    rightPowerDirectionUp = false;
  }
  if (rightPowerDirectionUp)
  {
    if (rightMotorPower+5>0)
    {
    rightMotorPower = leftMotorPower + 5;
    }
  }
  else if (!leftPowerDirectionUp)
  {
    if (rightMotorPower-5>0)
    {
    rightMotorPower = leftMotorPower - 5;
    }*/


void nudge()
{
  nudgeForward = joy1Btn(2);
  nudgeBackward = joy1Btn(4);
  nudgeLeft = joy1Btn(3);
  nudgeRight = joy1Btn(1);
  if (nudgeForward)
  {
    motor[leftMotor] = 25;
    motor[rightMotor] = 25;
    wait10Msec(500);
    while (joy1Btn(2))
    {
      wait10Msec(10);
    }
  }
  if (nudgeBackward)
  {
    motor[leftMotor] = -25;
    motor[rightMotor] = -25;
    while (joy1Btn(4))
    {
      wait10Msec(10);
    }
  }
  if (nudgeLeft)
  {
    motor[leftMotor] = -25;
    motor[rightMotor] = 25;
    while (joy1Btn(3))
    {
      wait10Msec(10);
    }
  }
  if (nudgeRight)
  {
    motor[leftMotor] = 25;
    motor[rightMotor] = -25;
    while (joy1Btn(1))
    {
      wait10Msec(10);
    }
  }

}

void motorControlProportional()
{
  int nMotorPower, nSteering1, nSteering2, nDirection;



  nMotorPower = joystick.joy1_y2;
  nSteering1  = joystick.joy1_y1;
  nSteering2  = joystick.joy1_y2;
  bool turn;
  int turnDir;

  /* Are we turning? Set the boolean to reflect that.
  if (nSteeringX > nSteeringY)
  {

    turn = true;
  }
  else
  {
    turn = false;
  }
  turnDir = 1;
  if (nMotorPower<0)
  {

    turnDir = -1;
  }
*/
  // Steering Control Switch. Checks if we are turning, and does the appropriate motor function.
  /*if (turn)
  {
      if (nSteeringX > 0)
      {
        // Turn Right
        motor[leftMotor]  = nSteeringX; // use power settings from Y-axis
        motor[rightMotor] = nSteeringX * (64 - nSteeringX) / 64;
      }
      else
      {
        // Turn Left
        motor[rightMotor] = nSteeringX; // use power settings from Y-axis
        motor[leftMotor]  = nSteeringX * (64 + nSteeringX) / 64;
      }
  }

   else
   {
     motor[leftMotor] = nMotorPower*-1;
     motor[rightMotor] = nMotorPower*-1;
   }*/
   if (joy1Btn(6))
   {
     motor[leftMotor] = nSteering1*-1/5;
     motor[rightMotor] = nSteering2*-1/5;
   }
   else
   {
     motor[leftMotor] = nSteering1*-1;
     motor[rightMotor] = nSteering2*-1;
   }








  if (nDirection < 0)
  {
    // Turn left

    motor[rightMotor] = nMotorPower; // use power settings from Y-axis
    motor[leftMotor]  = nMotorPower * (64 + nDirection) / 64;
  }
  else
  {
    // Turn right

    motor[leftMotor]  = nMotorPower; // use power settings from Y-axis
    motor[rightMotor] = nMotorPower * (64 - nDirection) / 64;
  }
}


void buttonControl()
{
  return;
}

task main()
{
  //servo[servo1] = 100;
  leftMotorPower = 1;
  rightMotorPower = 1;
  while (true)
  {
    getJoystickSettings(joystick);
    motorControlProportional();
    buttonControl();
    nudge();
  }
}
