#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    ,                     tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
void initServos(bool leftVar)
{
  int zero;
  if (leftVar)
  {
    zero = 9;
  }
  else
  {
    zero = 246;
  }
  servo[servo1] = zero;
  wait1Msec(1000);
}

task main()
{

  getJoystickSettings(joystick);
  bool wait;
  while (true)
  {
  wait = false;
  while (wait==false)
  {
    motor[leftMotor] = joystick.joy1_y1*-1;
  motor[rightMotor] = joystick.joy1_y2*-1;
    wait1Msec(1);
    if (joy1Btn(5))
    {
      wait = true;
    }
    else if (joy1Btn(6))
    {
      wait = true;
    }

  }
  bool direction;
  if (joy1Btn(5))
  {
    direction = true;
  }
  else if (joy1Btn(6))
  {
    direction = false;
  }
  joy1Btn(6);
  initServos(direction);
}
}

