#pragma config(Sensor, S4,     rotationSensor,      sensorLightInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
task main()
{
  while (true)
  {
    eraseDisplay();
      nxtDisplayStringAt(0,10,"Value: %d", SensorValue(rotationSensor));
      wait1Msec(10);
  }
}
