#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     HTSMUX,              sensorLowSpeed)
#pragma config(Motor,  mtr_S1_C2_1,     leftMotor,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C1_1,    shoulderServo,        tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    wristServo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    handServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo8,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo7,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    ,                     tServoStandard)
#pragma config(SrvoPosition,  Position01,            128, 128, 255, 255, 128, 128, 128, 128)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an Tetrix robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "FITBIncludes.c"
#include "HTGYRO-driver.h"
int totalTurn = 0;

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
     HTSMUXinit();//           Init sensor Muxer
  HTSMUXscanPorts(HTSMUX);//^^^^^^^^^^^^^^^^^
 definevars();
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
  HTGYROsetCal(msensor_S2_4, 0);//zero gyro


  return;
}

   int getGyro() {
    return HTGYROreadRot(msensor_S2_4);
  }
  void cronGyro() {
    int gyroZero = HTGYROreadRot(msensor_S2_4);
    totalTurn = totalTurn + (gyroZero-getGyro());
  }
  int getDiff() {
    return totalTurn;
  }



/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////
  ////                                                   ////
  ////    Add your robot specific autonomous code here.  ////
  ////                                                   ////
  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////



  while (totalTurn < 50)
  {
      eraseDisplay();
      motor[leftMotor] = 35;

      cronGyro();
      nxtDisplayTextLine(1, "Reading");
      // Read the current calibration offset and display it
      nxtDisplayTextLine(2, "Offset: %4d", HTGYROreadCal(msensor_S2_4));

      nxtDisplayClearTextLine(4);
      // Read the current rotational speed and display it
      nxtDisplayTextLine(4, "Gyro:   %4d", getGyro());
      nxtDisplayTextLine(6, "Diff:   %4d", getDiff());
      wait10Msec(2);
    }
motor[leftMotor] = 0;
motor[rightMotor] = 0;
  /*
  straightForTime(50, 870);
  wait1Msec(250);
  motor[rightMotor] = 30;
  wait1Msec(750);
  motor[rightMotor] = 0;
  wait1Msec(250);
  straightForTime(50, 775, true);*/

}
